# Temporal Overlap Analysis of Wildlife Species

https://www.reddit.com/r/academia/comments/1beit4y/obvious_chatgpt_in_a_published_paper/

This repository contains R code used to analyze the **temporal overlap** between species using camera-trap data. The workflow uses the [`overlap`](https://cran.r-project.org/package=overlap) package to estimate activity patterns and visualize overlap between species.

## 📦 Dependencies

Make sure the **overlap** package is installed:

```r
install.packages("overlap")
```

Load the package:

```r
library(overlap)
```

## 📊 Data Used

The code uses the built-in `kerinci` dataset from the **overlap** package. This dataset includes:

* `Time` — time of detection (scaled 0–1)
* `Sps` — species name (e.g., *tiger*, *macaque*)

```r
data(kerinci)
```

## 🕒 Converting Time to Circular Scale

To model daily activity patterns, time values (0–1) are converted into **radians** (0–2π), which is required for circular kernel density estimation.

```r
circulartime <- kerinci$Time * 2 * pi
kerinci$Timecirc <- kerinci$Time * 2 * pi
```

## 🐅 Tiger Activity Pattern

Subset the data for tigers:

```r
tiger <- kerinci[kerinci$Sps == "tiger", ]
tigertime <- tiger$Timecirc
```

Plot kernel density estimate of tiger activity:

```r
densityPlot(tigertime)
```

This visualizes the probability distribution of tiger detections across the 24-hour cycle.

## 🐒 Macaque Activity Pattern

Similarly, subset the data for macaques:

```r
macaque <- kerinci[kerinci$Sps == "macaque", ]
macaquetime <- macaque$Timecirc
```

Plot macaque activity:

```r
densityPlot(macaquetime)
```

## 🔁 Temporal Overlap Between Species

To visualize how much the two species overlap in their activity periods:

```r
overlapPlot(tigertime, macaquetime)
```

This function produces:

* Kernel density curves for each species
* Shaded region representing temporal overlap
* A visual summary of potential interaction or avoidance

## 📈 Interpretation

Activity overlap can help ecologists understand:

* Predator–prey interactions
* Niche partitioning
* Behavioral strategies for avoiding competition or predation

Higher overlap may suggest similar activity windows, while lower overlap indicates temporal separation.

---

## 📁 File Structure

```
├── R script (analysis code)
└── README.md (this document)
```

---

## ✨ Notes

* The dataset is already included in the package—no external data required.
* Plots generated by `densityPlot()` and `overlapPlot()` can be saved manually if needed.

---
